routes/admin.php
<?php

use App\Http\Controllers\PermissionsController;
use App\Http\Controllers\ProductCategoriesController;
use App\Http\Controllers\ProductsController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RoleController;
use App\Models\ProductCategories;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*------ Auth ------*/
Auth::routes();

/*------ Admin ------*/
Route::prefix('admin')->middleware('auth')->name('admin.')->group( function(){

    /*------ User ------*/
    Route::prefix('user')->name('user.')->middleware('hasRole:admin,visitor')->group( function(){
        $class = UserController::class;
        Route::get('/', [$class, 'index'])->name('index')->middleware('hasPermission:user.view');
        Route::post('store', [$class, 'store'])->name('store')->middleware('hasPermission:user.create');
        Route::get('edit/{id}', [$class, 'edit'])->name('edit')->middleware('hasPermission:user.update');
        Route::post('update', [$class, 'update'])->name('update')->middleware('hasPermission:user.update');
        Route::delete('delete/{id}', [$class, 'delete'])->name('delete')->middleware('hasPermission:user.delete');
    });

    /*------ Role ------*/
    Route::prefix('role')->name('role.')->middleware('hasRole:admin,visitor')->group( function(){
        $class = RoleController::class;
        Route::get('/', [$class, 'index'])->name('index')->middleware('hasPermission:role.view');
        Route::post('store', [$class, 'store'])->name('store')->middleware('hasPermission:role.view');
        Route::get('edit/{id}', [$class, 'edit'])->name('edit')->middleware('hasPermission:role.view');
        Route::post('update', [$class, 'update'])->name('update')->middleware('hasPermission:role.view');
        Route::delete('delete/{id}', [$class, 'delete'])->name('delete')->middleware('hasPermission:role.view');
    });

    /*------ Permission ------*/
    Route::prefix('permission')->name('permission.')->middleware('hasRole:admin,visitor')->group( function(){
        $class = PermissionsController::class;
        Route::get('/', [$class, 'index'])->name('index')->middleware('hasPermission:permission.view');
        Route::post('store', [$class, 'store'])->name('store')->middleware('hasPermission:permission.create');
        Route::post('update', [$class, 'update'])->name('update')->middleware('hasPermission:permission.update');
        Route::delete('delete/{id}', [$class, 'delete'])->name('delete')->middleware('hasPermission:permission.delete');
    });
    
    /*------ Product Category ------*/
    Route::prefix('product-categories')->name('product-categories.')->middleware('hasRole:admin,visitor')->group( function(){
        $class = ProductCategoriesController::class;
        Route::get('/', [$class, 'index'])->name('index')->middleware('hasPermission:productCategories.view');
        Route::post('store', [$class, 'store'])->name('store')->middleware('hasPermission:productCategories.create');
        Route::post('update', [$class, 'update'])->name('update')->middleware('hasPermission:productCategories.update');
        Route::delete('delete/{id}', [$class, 'delete'])->name('delete')->middleware('hasPermission:productCategories.delete');
    });
    
    /*------ Product ------*/
    Route::prefix('product')->name('product.')->middleware('hasRole:admin,visitor')->group( function(){
        $class = ProductsController::class;
        Route::get('/', [$class, 'index'])->name('index')->middleware('hasPermission:product.view');
        Route::post('store', [$class, 'store'])->name('store')->middleware('hasPermission:product.create');
        Route::get('edit/{id}', [$class, 'edit'])->name('edit')->middleware('hasPermission:product.update');
        Route::post('update', [$class, 'update'])->name('update')->middleware('hasPermission:product.update');
        Route::delete('delete/{id}', [$class, 'delete'])->name('delete')->middleware('hasPermission:product.delete');
    });
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

require("admin.php");

Route::get('/', function(){
    return view('welcome');
});

app/Models/Products.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Products extends Model
{
    use HasFactory;

    protected $fillable = [
        'name', 'description', 'image', 'price_base', 'price_total',
        'category_id', 'quantity', 'status', 'slug'
    ];

    public function category()
    {
        return $this->belongsTo("App\Models\ProductCategories", "category_id");
    }

    public function getImage()
    {
        return asset("picture/product/".$this->image);
    }

    public function scopeWhereHasCategory($query, $category)
    {
        return $category ? $query->whereHas('category', function(Builder $query) use($category){
            $query->where('name', $category);
        }) : null;
    }

    public function scopeWhereHasKey($query, $key)
    {
        return $key ? $query->where('name', 'like', "%{$key}%")
            ->orWhere('description', 'like', "%{$key}%") : null;
    }
}

app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProductsRequest;
use App\Models\Products;
use App\Services\ProductCategoriesService;
use App\Services\ProductsService;
use Illuminate\Http\Request;

class ProductsController extends Controller
{
    protected $productsService;
    protected $pathView = 'admin.products.';

    public function __construct(ProductsService $productsService, ProductCategoriesService $productCategoriesService)
    {
        $this->productsService = $productsService;
        $this->productCategoriesService = $productCategoriesService;
    }

    public function index(Request $request)
    {
        $products = $this->productsService->searchDataByKey($request);
        $categories = $this->productCategoriesService->getAll();
        return view($this->pathView.'index', compact('products', 'categories'));
    }

    public function store(ProductsRequest $request)
    {
        $this->productsService->saveData($request->all());
        return $this->sendResponse("Thêm mới thành công");
    }

    public function edit($id)
    {
        $product = $this->productsService->getDataByID($id);
        return response()->json([
            'status_code' => 200,
            'product' => $product,
        ]);
    }

    public function update(ProductsRequest $request)
    {
        $this->productsService->updateByID($request->all());
        return $this->sendResponse("Cập nhật thành công");
    }

    public function delete($id)
    {
        $this->productsService->deleteByID($id);
        return $this->sendResponse();
    }
}

resources/views/admin/products/create.blade.php
<!-- Modal -->
<div class="modal fade" id="create-product" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Thêm mới Product</h5>
            </div>
            <form data-url="{{ route('admin.product.store') }}" id="formCreateProduct" method="POST">
                @csrf
                <div class="modal-body">
                    <div class="row">
                        <div class="form-group col-md-6 mb-3">
                            <label for="">Name</label>
                            <input type="text" name="name" class="form-control input-name">
                            <span class="text-danger d-none" id="nameError"></span>
                        </div>
                        <div class="form-group col-md-6 mb-3">
                            <label for="">Slug</label>
                            <input type="text" name="slug" class="form-control input-slug">
                        </div>
                    </div>
                    <div class="form-group mb-3">
                        <label for="">Description</label>
                        <textarea name="description" id="" class="form-control" rows="5"></textarea>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-6 mb-3">
                            <label for="">Price Base</label>
                            <input type="text" name="price_base" class="form-control">
                        </div>
                        <div class="form-group col-md-6 mb-3">
                            <label for="">Price Final</label>
                            <input type="text" name="price_total" class="form-control">
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-6 mb-3">   
                            <label for="">Quantity</label>
                            <input type="number" name="quantity" class="form-control">
                        </div>
                        <div class="form-group col-md-6 mb-3 d-flex flex-column">
                            <label for="">Category</label>
                            <select name="category_id" id="select-category">
                                @foreach ($categories as $item)
                                    <option value="{{ $item->id }}">{{ $item->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="form-group mb-3">
                        <label for="">Iamge</label>
                        <input type="file" name="image" class="form-control">
                    </div>
                    <div class="form-group">
                        <label>
                            <input type="hidden" name="status" value="inactive">
                            <input type="checkbox" name="status" value="active">
                            Active
                        </label>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Đóng</button>
                    <button type="submit" class="btn btn-primary">Gửi</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/admin/products/index.blade.php
@extends('admin.layouts.main')

@section('content')
    <div class="page-content">
        <h4 class="text-uppercase">Product</h4>
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="d-flex align-items-center justify-content-between">
                        @can('product.create')
                            <div class="col-lg-4 col-xl-4">
                                <a href="" class="btn btn-primary mb-3 mb-lg-0" data-bs-toggle="modal"
                                    data-bs-target="#create-product">
                                    <i class="bx bxs-plus-square"></i>Thêm mới
                                </a>
                            </div>
                        @endcan
                        <div class="position-relative">
                            <form action="{{ route("admin.product.index") }}" method="GET" id="formSearch">
                                <div class="d-flex align-items-center">
                                    <div class="search-option">
                                        <select id="select-role" name="search_option">
                                            @foreach ($categories as $category)
                                                <option value="{{ $category->name }}" {{ request("search_option") == $category->name ? "selected":"" }}>{{ $category->name }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                    <div class="search-input position-relative" style="margin:0 10px">
                                        <input type="text" class="form-control ps-5" placeholder="Search Anything..." name="search_key" value="{{ request('search_key') }}"> 
                                        <span class="position-absolute top-50 product-show translate-middle-y">
                                            <i class="bx bx-search"></i>
                                        </span>
                                    </div>
                                    <button type="submit" class="btn btn-success">Search</button>
                                    <a href="#" class="btn btn-secondary clear-search" style="margin-left: 10px">Clear</a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                @include("admin.products.list")
            </div>
            {{ $products->links() }}
        </div>

        {{-- Modal for create product --}}
        @include('admin.products.create')
        {{-- Modal for create product --}}
        @include('admin.products.update')
    </div>
@endsection

resources/views/admin/products/list.blade.php
<table class="table mt-4">
    <thead class="table-dark">
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Name</th>
            <th scope="col">Description</th>
            <th scope="col">Image</th>
            <th scope="col">Price Base</th>
            <th scope="col">Price Final</th>
            <th scope="col">Category</th>
            <th scope="col">Quantity</th>
            <th scope="col">Status</th>
            <th scope="col">Created At</th>
            @can(['product.delete', 'product.update'])
                <th scope="col">Actions</th>
            @endcan
        </tr>
    </thead>
    <tbody>
        @foreach ($products as $item)
            <tr>
                <td>{{ $item->id }}</td>
                <td>{{ $item->name }}</td>
                <td>{{ $item->description }}</td>
                <td>
                    <img src="{{ $item->getImage() }}" alt="{{ $item->name }}" class="image-show">
                </td>
                <td>{{ $item->price_base }}</td>
                <td>{{ $item->price_total }}</td>
                @php
                    $category = $item->category;
                    $category_name = @$category->name;
                @endphp
                <td>{{ $category_name }}</td>
                <td>{{ $item->quantity }}</td>
                @if($item->status == "active")
                    <td><span class="badge bg-success">{{ $item->status }}</span></td>
                @else
                    <td><span class="badge bg-danger">{{ $item->status }}</span></td>
                @endif
                <td>{{ date_format($item->created_at, 'd/m/Y H:i:s') }}</td>
                <td>
                    @can(['product.update'])
                        <a class="btn btn-success update-product-button"
                            data-bs-toggle="modal" data-bs-target="#update-product" 
                            data-url="{{ route('admin.product.edit', ['id' => $item->id]) }}">
                            <i class="bx bx-edit mr-0"></i>
                        </a>
                    @endcan

                    @can(['product.delete'])
                        <a class="btn btn-danger delete-button"
                            data-url="{{ route('admin.product.delete', ['id' => $item->id]) }}">
                            <i class="bx bx-trash mr-0"></i>
                        </a>
                    @endcan
                </td>
            </tr>
        @endforeach
    </tbody>
</table>

resources/views/admin/products/update.blade.php
<!-- Modal -->
<div class="modal fade" id="update-product" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Cập nhật Product</h5>
            </div>
            <form data-url="{{ route('admin.product.update') }}" id="formUpdateProduct" method="POST">
                @csrf
                <input type="hidden" name="id" id="id_product">
                <div class="modal-body">
                    <div class="row">
                        <div class="form-group col-md-6 mb-3">
                            <label for="">Name</label>
                            <input type="text" name="name" class="form-control input-name" id="name-product">
                            <span class="text-danger d-none" id="nameUpdateError"></span>
                        </div>
                        <div class="form-group col-md-6 mb-3">
                            <label for="">Slug</label>
                            <input type="text" name="slug" class="form-control input-slug" id="name-slug">
                        </div>
                    </div>
                    <div class="form-group mb-3">
                        <label for="">Description</label>
                        <textarea name="description" class="form-control" rows="5" id="description-product"></textarea>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-6 mb-3">
                            <label for="">Price Base</label>
                            <input type="text" name="price_base" class="form-control" id="price_base-product">
                        </div>
                        <div class="form-group col-md-6 mb-3">
                            <label for="">Price Final</label>
                            <input type="text" name="price_total" class="form-control" id="price_final-product">
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-6 mb-3">   
                            <label for="">Quantity</label>
                            <input type="number" name="quantity" class="form-control" id="quantity-product">
                        </div>
                        <div class="form-group col-md-6 mb-3 d-flex flex-column">
                            <label for="">Category</label>
                            <select name="category_id" id="select-category-update">
                                @foreach ($categories as $item)
                                    <option value="{{ $item->id }}">{{ $item->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="form-group mb-3" id="image-product">
                        <label for="">Iamge</label>
                        <input type="file" name="image" class="form-control">
                    </div>
                    <div class="form-group">
                        <label>
                            <input type="hidden" name="status" value="inactive">
                            <input type="checkbox" name="status" value="active" id="status-product">
                            Active
                        </label>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Đóng</button>
                    <button type="submit" class="btn btn-primary">Gửi</button>
                </div>
            </form>
        </div>
    </div>
</div>