routes/admin.php
<?php

use App\Http\Controllers\PermissionsController;
use App\Http\Controllers\ProductCategoriesController;
use App\Http\Controllers\ProductsController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RoleController;
use App\Models\ProductCategories;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*------ Auth ------*/
Auth::routes();

/*------ Admin ------*/
Route::prefix('admin')->middleware('auth')->name('admin.')->group( function(){

    /*------ User ------*/
    Route::prefix('user')->name('user.')->middleware('hasRole:admin,visitor')->group( function(){
        $class = UserController::class;
        Route::get('/', [$class, 'index'])->name('index')->middleware('hasPermission:user.view');
        Route::post('store', [$class, 'store'])->name('store')->middleware('hasPermission:user.create');
        Route::get('edit/{id}', [$class, 'edit'])->name('edit')->middleware('hasPermission:user.update');
        Route::post('update', [$class, 'update'])->name('update')->middleware('hasPermission:user.update');
        Route::delete('delete/{id}', [$class, 'delete'])->name('delete')->middleware('hasPermission:user.delete');
    });

    /*------ Role ------*/
    Route::prefix('role')->name('role.')->middleware('hasRole:admin,visitor')->group( function(){
        $class = RoleController::class;
        Route::get('/', [$class, 'index'])->name('index')->middleware('hasPermission:role.view');
        Route::post('store', [$class, 'store'])->name('store')->middleware('hasPermission:role.view');
        Route::get('edit/{id}', [$class, 'edit'])->name('edit')->middleware('hasPermission:role.view');
        Route::post('update', [$class, 'update'])->name('update')->middleware('hasPermission:role.view');
        Route::delete('delete/{id}', [$class, 'delete'])->name('delete')->middleware('hasPermission:role.view');
    });

    /*------ Permission ------*/
    Route::prefix('permission')->name('permission.')->middleware('hasRole:admin,visitor')->group( function(){
        $class = PermissionsController::class;
        Route::get('/', [$class, 'index'])->name('index')->middleware('hasPermission:permission.view');
        Route::post('store', [$class, 'store'])->name('store')->middleware('hasPermission:permission.create');
        Route::post('update', [$class, 'update'])->name('update')->middleware('hasPermission:permission.update');
        Route::delete('delete/{id}', [$class, 'delete'])->name('delete')->middleware('hasPermission:permission.delete');
    });
    
    /*------ Product Category ------*/
    Route::prefix('product-categories')->name('product-categories.')->middleware('hasRole:admin,visitor')->group( function(){
        $class = ProductCategoriesController::class;
        Route::get('/', [$class, 'index'])->name('index')->middleware('hasPermission:productCategories.view');
        Route::post('store', [$class, 'store'])->name('store')->middleware('hasPermission:productCategories.create');
        Route::post('update', [$class, 'update'])->name('update')->middleware('hasPermission:productCategories.update');
        Route::delete('delete/{id}', [$class, 'delete'])->name('delete')->middleware('hasPermission:productCategories.delete');
    });
    
    /*------ Product ------*/
    Route::prefix('product')->name('product.')->middleware('hasRole:admin,visitor')->group( function(){
        $class = ProductsController::class;
        Route::get('/', [$class, 'index'])->name('index')->middleware('hasPermission:product.view');
        Route::post('store', [$class, 'store'])->name('store')->middleware('hasPermission:product.create');
        Route::get('edit/{id}', [$class, 'edit'])->name('edit')->middleware('hasPermission:product.update');
        Route::post('update', [$class, 'update'])->name('update')->middleware('hasPermission:product.update');
        Route::delete('delete/{id}', [$class, 'delete'])->name('delete')->middleware('hasPermission:product.delete');
    });
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

require("admin.php");

Route::get('/', function(){
    return view('welcome');
});

app/Http/Controllers/ProductCategoriesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProductCategoriesRequest;
use App\Models\ProductCategories;
use App\Services\ProductCategoriesService;
use Illuminate\Http\Request;

class ProductCategoriesController extends Controller
{
    protected $productCategoriesService;

    public function __construct(ProductCategoriesService $productCategoriesService)
    {
        $this->productCategoriesService = $productCategoriesService;
    }

    public function index(Request $request)
    {
        $productCategories = $this->productCategoriesService->searchDataByKey($request->search_key);
        return view('admin.productCategories.index', compact('productCategories'));
    }

    public function store(ProductCategoriesRequest $request)
    {
        $this->productCategoriesService->saveData($request->all());
        return $this->sendResponse("Thêm mới thành công");
    }

    public function update(ProductCategoriesRequest $request)
    {
        $this->productCategoriesService->updateByID($request->all());
        return $this->sendResponse("Cập nhật thành công");
    }

    public function delete($id)
    {
        $this->productCategoriesService->deleteByID($id);
        return $this->sendResponse();
    }
}

resources/views/admin/productCategories/create.blade.php
<!-- Modal -->
<div class="modal fade" id="create-product-categories" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Thêm mới Product Category</h5>
            </div>
            <form data-url="{{ route('admin.product-categories.store') }}" id="formCreateProductCategories" method="POST">
                @csrf
                <div class="modal-body">
                    <div class="form-group mb-3">
                        <label for="">Name</label>
                        <input type="text" name="name" class="form-control input-name">
                        <span class="text-danger d-none" id="nameError"></span>
                    </div>
                    <div class="form-group mb-3">
                        <label for="">Slug</label>
                        <input type="text" name="slug" class="form-control input-slug">
                        <span class="text-danger d-none" id="nameError"></span>
                    </div>
                    <div class="form-group mb-5">
                        <label>
                            <input type="hidden" name="status" value="inactive">
                            <input type="checkbox" name="status" value="active">
                            Active
                        </label>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Đóng</button>
                    <button type="submit" class="btn btn-primary">Gửi</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/admin/productCategories/index.blade.php
@extends('admin.layouts.main')

@section('content')
    <div class="page-content">
        <h4 class="text-uppercase">Product Categories</h4>
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="d-flex align-items-center justify-content-between">
                        @can('productCategories.create')
                            <div class="col-lg-4 col-xl-4">
                                <a href="" class="btn btn-primary mb-3 mb-lg-0" data-bs-toggle="modal"
                                    data-bs-target="#create-product-categories">
                                    <i class="bx bxs-plus-square"></i>Thêm mới
                                </a>
                            </div>
                        @endcan
                        @include('admin.components.search', ['route' => route("admin.product-categories.index")])
                    </div>
                </div>
                @include("admin.components.notification")
                @include("admin.productCategories.list")
            </div>
        </div>

        {{-- Modal for create product --}}
        @include('admin.productCategories.create')
        {{-- Modal for create product --}}
        @include('admin.productCategories.update')
    </div>
@endsection

resources/views/admin/productCategories/list.blade.php
<table class="table mt-4">
    <thead class="table-dark">
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Name</th>
            <th scope="col">Slug</th>
            <th scope="col">Status</th>
            <th scope="col">Created At</th>
            @can(['productCategories.delete', 'productCategories.update'])
                <th scope="col">Actions</th>
            @endcan
        </tr>
    </thead>
    <tbody>
        @foreach ($productCategories as $item)
            <tr>
                <td>{{ $item->id }}</td>
                <td>{{ $item->name }}</td>
                <td>{{ $item->slug }}</td>
                @if($item->status == "active")
                    <td><span class="badge bg-success">{{ $item->status }}</span></td>
                @else
                    <td><span class="badge bg-danger">{{ $item->status }}</span></td>
                @endif
                <td>{{ date_format($item->created_at, 'd/m/Y H:i:s') }}</td>
                <td>
                    @can(['productCategories.update'])
                        <a class="btn btn-success update-productC-button"
                            data-bs-toggle="modal" data-bs-target="#update-productCategories">
                            <i class="bx bx-edit mr-0"></i>
                        </a>
                    @endcan

                    @can(['productCategories.delete'])
                        <a class="btn btn-danger delete-button"
                            data-url="{{ route('admin.product-categories.delete', ['id' => $item->id]) }}">
                            <i class="bx bx-trash mr-0"></i>
                        </a>
                    @endcan
                </td>
            </tr>
        @endforeach
    </tbody>
</table>

resources/views/admin/productCategories/update.blade.php
<div class="modal fade" id="update-productCategories" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Cập nhật role</h5>
            </div>
            <form id="formUpdateProductCategories" method="POST" data-url="{{ route('admin.product-categories.update') }}">
                @csrf
                <div class="modal-body">
                    <input type="hidden" name="id" id="id-productCategories">
                    <div class="form-group mb-3">
                        <label for="">Name</label>
                        <input type="text" name="name" class="form-control" id="name-productCategories">
                        <span class="text-danger d-none" id="nameUpdateError"></span>
                    </div>
                    <div class="form-group mb-3">
                        <label for="">Slug</label>
                        <input type="text" name="slug" class="form-control" id="slug-productCategories">
                    </div>
                    <div class="form-group mb-5">
                        <label>
                            <input type="hidden" name="status" value="inactive">
                            <input type="checkbox" name="status" value="active" id="active-productCategories">
                            Active
                        </label>
                    </div>
                   
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Đóng</button>
                    <button type="submit" class="btn btn-primary submit-update">Gửi</a>
                </div>
            </form>
        </div>
    </div>
</div>