routes/admin.php
<?php

use App\Http\Controllers\PermissionsController;
use App\Http\Controllers\ProductCategoriesController;
use App\Http\Controllers\ProductsController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RoleController;
use App\Models\ProductCategories;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*------ Auth ------*/
Auth::routes();

/*------ Admin ------*/
Route::prefix('admin')->middleware('auth')->name('admin.')->group( function(){

    /*------ User ------*/
    Route::prefix('user')->name('user.')->middleware('hasRole:admin,visitor')->group( function(){
        $class = UserController::class;
        Route::get('/', [$class, 'index'])->name('index')->middleware('hasPermission:user.view');
        Route::post('store', [$class, 'store'])->name('store')->middleware('hasPermission:user.create');
        Route::get('edit/{id}', [$class, 'edit'])->name('edit')->middleware('hasPermission:user.update');
        Route::post('update', [$class, 'update'])->name('update')->middleware('hasPermission:user.update');
        Route::delete('delete/{id}', [$class, 'delete'])->name('delete')->middleware('hasPermission:user.delete');
    });

    /*------ Role ------*/
    Route::prefix('role')->name('role.')->middleware('hasRole:admin,visitor')->group( function(){
        $class = RoleController::class;
        Route::get('/', [$class, 'index'])->name('index')->middleware('hasPermission:role.view');
        Route::post('store', [$class, 'store'])->name('store')->middleware('hasPermission:role.view');
        Route::get('edit/{id}', [$class, 'edit'])->name('edit')->middleware('hasPermission:role.view');
        Route::post('update', [$class, 'update'])->name('update')->middleware('hasPermission:role.view');
        Route::delete('delete/{id}', [$class, 'delete'])->name('delete')->middleware('hasPermission:role.view');
    });

    /*------ Permission ------*/
    Route::prefix('permission')->name('permission.')->middleware('hasRole:admin,visitor')->group( function(){
        $class = PermissionsController::class;
        Route::get('/', [$class, 'index'])->name('index')->middleware('hasPermission:permission.view');
        Route::post('store', [$class, 'store'])->name('store')->middleware('hasPermission:permission.create');
        Route::post('update', [$class, 'update'])->name('update')->middleware('hasPermission:permission.update');
        Route::delete('delete/{id}', [$class, 'delete'])->name('delete')->middleware('hasPermission:permission.delete');
    });
    
    /*------ Product Category ------*/
    Route::prefix('product-categories')->name('product-categories.')->middleware('hasRole:admin,visitor')->group( function(){
        $class = ProductCategoriesController::class;
        Route::get('/', [$class, 'index'])->name('index')->middleware('hasPermission:productCategories.view');
        Route::post('store', [$class, 'store'])->name('store')->middleware('hasPermission:productCategories.create');
        Route::post('update', [$class, 'update'])->name('update')->middleware('hasPermission:productCategories.update');
        Route::delete('delete/{id}', [$class, 'delete'])->name('delete')->middleware('hasPermission:productCategories.delete');
    });
    
    /*------ Product ------*/
    Route::prefix('product')->name('product.')->middleware('hasRole:admin,visitor')->group( function(){
        $class = ProductsController::class;
        Route::get('/', [$class, 'index'])->name('index')->middleware('hasPermission:product.view');
        Route::post('store', [$class, 'store'])->name('store')->middleware('hasPermission:product.create');
        Route::get('edit/{id}', [$class, 'edit'])->name('edit')->middleware('hasPermission:product.update');
        Route::post('update', [$class, 'update'])->name('update')->middleware('hasPermission:product.update');
        Route::delete('delete/{id}', [$class, 'delete'])->name('delete')->middleware('hasPermission:product.delete');
    });
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

require("admin.php");

Route::get('/', function(){
    return view('welcome');
});

resources/views/admin/components/alert.blade.php
<div class="sweet-alert">
    <div class="alert alert-success border-0 bg-success alert-dismissible fade show py-2">
        <div class="d-flex align-items-center">
            <div class="font-35 text-white"><i class="bx bxs-check-circle"></i>
            </div>
            <div class="ms-3">
                <h6 class="mb-0 text-white">Success Alerts</h6>
                <div class="text-white" id="message"></div>
            </div>
        </div>
    </div>
</div>

resources/views/admin/components/config.blade.php
<div class="switcher-wrapper">
    <div class="switcher-btn"> <i class='bx bx-cog bx-spin'></i>
    </div>
    <div class="switcher-body">
        <div class="d-flex align-items-center">
            <h5 class="mb-0 text-uppercase">Theme Customizer</h5>
            <button type="button" class="btn-close ms-auto close-switcher" aria-label="Close"></button>
        </div>
        <hr/>
        <h6 class="mb-0">Theme Styles</h6>
        <hr/>
        <div class="d-flex align-items-center justify-content-between">
            <div class="form-check">
                <input class="form-check-input" type="radio" name="flexRadioDefault" id="lightmode" checked>
                <label class="form-check-label" for="lightmode">Light</label>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="radio" name="flexRadioDefault" id="darkmode">
                <label class="form-check-label" for="darkmode">Dark</label>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="radio" name="flexRadioDefault" id="semidark">
                <label class="form-check-label" for="semidark">Semi Dark</label>
            </div>
        </div>
        <hr/>
        <div class="form-check">
            <input class="form-check-input" type="radio" id="minimaltheme" name="flexRadioDefault">
            <label class="form-check-label" for="minimaltheme">Minimal Theme</label>
        </div>
        <hr/>
        <h6 class="mb-0">Header Colors</h6>
        <hr/>
        <div class="header-colors-indigators">
            <div class="row row-cols-auto g-3">
                <div class="col">
                    <div class="indigator headercolor1" id="headercolor1"></div>
                </div>
                <div class="col">
                    <div class="indigator headercolor2" id="headercolor2"></div>
                </div>
                <div class="col">
                    <div class="indigator headercolor3" id="headercolor3"></div>
                </div>
                <div class="col">
                    <div class="indigator headercolor4" id="headercolor4"></div>
                </div>
                <div class="col">
                    <div class="indigator headercolor5" id="headercolor5"></div>
                </div>
                <div class="col">
                    <div class="indigator headercolor6" id="headercolor6"></div>
                </div>
                <div class="col">
                    <div class="indigator headercolor7" id="headercolor7"></div>
                </div>
                <div class="col">
                    <div class="indigator headercolor8" id="headercolor8"></div>
                </div>
            </div>
        </div>

        <hr/>
        <h6 class="mb-0">Sidebar Backgrounds</h6>
        <hr/>
        <div class="header-colors-indigators">
            <div class="row row-cols-auto g-3">
                <div class="col">
                    <div class="indigator sidebarcolor1" id="sidebarcolor1"></div>
                </div>
                <div class="col">
                    <div class="indigator sidebarcolor2" id="sidebarcolor2"></div>
                </div>
                <div class="col">
                    <div class="indigator sidebarcolor3" id="sidebarcolor3"></div>
                </div>
                <div class="col">
                    <div class="indigator sidebarcolor4" id="sidebarcolor4"></div>
                </div>
                <div class="col">
                    <div class="indigator sidebarcolor5" id="sidebarcolor5"></div>
                </div>
                <div class="col">
                    <div class="indigator sidebarcolor6" id="sidebarcolor6"></div>
                </div>
                <div class="col">
                    <div class="indigator sidebarcolor7" id="sidebarcolor7"></div>
                </div>
                <div class="col">
                    <div class="indigator sidebarcolor8" id="sidebarcolor8"></div>
                </div>
            </div>
        </div>

    </div>
</div>

resources/views/admin/components/notification.blade.php
@if( session('updated') )
    <div class="alert alert-success border-0 bg-success alert-dismissible fade show mt-3">
        <div class="d-flex align-items-center">
            <div class="font-35 text-white"><i class="bx bxs-check-circle"></i>
            </div>
            <div class="ms-3">
                <h6 class="mb-0 text-white">Success Alert</h6>
                <div class="text-white">{{session('updated')}}</div>
            </div>
        </div>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
@endif

resources/views/admin/components/search.blade.php
<div class="position-relative">
    <form action="{{ $route }}" method="GET">
        <input type="text" class="form-control ps-5" placeholder="Search Anything..." name="search_key" value="{{ request('search_key') }}"> 
        <span class="position-absolute top-50 product-show translate-middle-y">
            <i class="bx bx-search"></i>
        </span>
    </form>
</div>

resources/views/admin/components/sidebar.blade.php
<div class="sidebar-wrapper" data-simplebar="true">
    <div class="sidebar-header">
        <div>
            <img src="{{ asset('admin/assets/images/logo-icon.png') }}" class="logo-icon" alt="logo icon">
        </div>
        <div>
            <h4 class="logo-text">Deha</h4>
        </div>
        <div class="toggle-icon ms-auto"><i class='bx bx-arrow-to-left'></i>
        </div>
    </div>
    <!--navigation-->
    <ul class="metismenu" id="menu">
        <li class="menu-label">Resources</li>
        <li>
            <a href="javascript:;" class="has-arrow">
                <div class="parent-icon"><i class='bx bx-cart-alt'></i>
                </div>
                <div class="menu-title">Sản phẩm</div>
            </a>
            <ul>
                <li> <a href="{{ route('admin.product.index') }}"><i class="bx bx-right-arrow-alt"></i>Danh sách sản phẩm</a>
                </li>
                <li> <a href="{{ route('admin.product-categories.index') }}"><i class="bx bx-right-arrow-alt"></i>Danh sách danh mục</a>
                </li>
            </ul>
        </li>
        <li>
            <a href="javascript:;" class="has-arrow">
                <div class="parent-icon"><i class='bx bx-user'></i>
                </div>
                <div class="menu-title">User</div>
            </a>
            <ul>
                <li> <a href="{{ route('admin.user.index') }}"><i class="bx bx-right-arrow-alt"></i>Danh sách user</a>
                </li>
            </ul>
        </li>
        <li>
            <a href="javascript:;" class="has-arrow">
                <div class="parent-icon"><i class='bx bx-lock'></i>
                </div>
                <div class="menu-title">Role</div>
            </a>
            <ul>
                <li> <a href="{{ route('admin.role.index') }}"><i class="bx bx-right-arrow-alt"></i>Danh sách role</a>
                </li>
            </ul>
        </li>

        <li>
            <a href="javascript:;" class="has-arrow">
                <div class="parent-icon"><i class='bx bx-lock'></i>
                </div>
                <div class="menu-title">Permissions</div>
            </a>
            <ul>
                <li> <a href="{{ route('admin.permission.index') }}"><i class="bx bx-right-arrow-alt"></i>Danh sách permissions</a>
                </li>
            </ul>
        </li>

    </ul>
    <!--end navigation-->
</div>