routes/admin.php
<?php

use App\Http\Controllers\PermissionsController;
use App\Http\Controllers\ProductCategoriesController;
use App\Http\Controllers\ProductsController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RoleController;
use App\Models\ProductCategories;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*------ Auth ------*/
Auth::routes();

/*------ Admin ------*/
Route::prefix('admin')->middleware('auth')->name('admin.')->group( function(){

    /*------ User ------*/
    Route::prefix('user')->name('user.')->middleware('hasRole:admin,visitor')->group( function(){
        $class = UserController::class;
        Route::get('/', [$class, 'index'])->name('index')->middleware('hasPermission:user.view');
        Route::post('store', [$class, 'store'])->name('store')->middleware('hasPermission:user.create');
        Route::get('edit/{id}', [$class, 'edit'])->name('edit')->middleware('hasPermission:user.update');
        Route::post('update', [$class, 'update'])->name('update')->middleware('hasPermission:user.update');
        Route::delete('delete/{id}', [$class, 'delete'])->name('delete')->middleware('hasPermission:user.delete');
    });

    /*------ Role ------*/
    Route::prefix('role')->name('role.')->middleware('hasRole:admin,visitor')->group( function(){
        $class = RoleController::class;
        Route::get('/', [$class, 'index'])->name('index')->middleware('hasPermission:role.view');
        Route::post('store', [$class, 'store'])->name('store')->middleware('hasPermission:role.view');
        Route::get('edit/{id}', [$class, 'edit'])->name('edit')->middleware('hasPermission:role.view');
        Route::post('update', [$class, 'update'])->name('update')->middleware('hasPermission:role.view');
        Route::delete('delete/{id}', [$class, 'delete'])->name('delete')->middleware('hasPermission:role.view');
    });

    /*------ Permission ------*/
    Route::prefix('permission')->name('permission.')->middleware('hasRole:admin,visitor')->group( function(){
        $class = PermissionsController::class;
        Route::get('/', [$class, 'index'])->name('index')->middleware('hasPermission:permission.view');
        Route::post('store', [$class, 'store'])->name('store')->middleware('hasPermission:permission.create');
        Route::post('update', [$class, 'update'])->name('update')->middleware('hasPermission:permission.update');
        Route::delete('delete/{id}', [$class, 'delete'])->name('delete')->middleware('hasPermission:permission.delete');
    });
    
    /*------ Product Category ------*/
    Route::prefix('product-categories')->name('product-categories.')->middleware('hasRole:admin,visitor')->group( function(){
        $class = ProductCategoriesController::class;
        Route::get('/', [$class, 'index'])->name('index')->middleware('hasPermission:productCategories.view');
        Route::post('store', [$class, 'store'])->name('store')->middleware('hasPermission:productCategories.create');
        Route::post('update', [$class, 'update'])->name('update')->middleware('hasPermission:productCategories.update');
        Route::delete('delete/{id}', [$class, 'delete'])->name('delete')->middleware('hasPermission:productCategories.delete');
    });
    
    /*------ Product ------*/
    Route::prefix('product')->name('product.')->middleware('hasRole:admin,visitor')->group( function(){
        $class = ProductsController::class;
        Route::get('/', [$class, 'index'])->name('index')->middleware('hasPermission:product.view');
        Route::post('store', [$class, 'store'])->name('store')->middleware('hasPermission:product.create');
        Route::get('edit/{id}', [$class, 'edit'])->name('edit')->middleware('hasPermission:product.update');
        Route::post('update', [$class, 'update'])->name('update')->middleware('hasPermission:product.update');
        Route::delete('delete/{id}', [$class, 'delete'])->name('delete')->middleware('hasPermission:product.delete');
    });
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

require("admin.php");

Route::get('/', function(){
    return view('welcome');
});

app/Models/Permissions.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Permissions extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'action'];

    public function roles()
    {
        return $this->belongsToMany('App\Models\Role', 'role_permissions', 'id_permission', 'id_role');
    }

    public function scopeSearchMultiple($query, $key)
    {
        return $key ? $query->where('name', 'like', "%{$key}%")
            ->orWhere('action', 'like', "%{$key}%") : null;
    }
}

app/Http/Controllers/PermissionsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\PermissionRequest;
use App\Models\Permissions;
use App\Services\PermissionsService;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class PermissionsController extends Controller
{
    protected $pathView = 'admin.permissions.';
    protected $permissionsService;

    public function __construct(PermissionsService $permissionsService)
    {
        $this->permissionsService = $permissionsService;
    }

    public function index(Request $request)
    {   
        $permissions = $this->permissionsService->searchDataByKey($request->search_key);
        return view($this->pathView.'index', compact('permissions'));
    }

    public function store(PermissionRequest $request)
    {
        $this->permissionsService->saveData($request->all());
        return $this->sendResponse("Thêm mới thành công");
    }

    public function update(PermissionRequest $request)
    {
        $this->permissionsService->updateByID($request->all());
        return $this->sendResponse("Cập nhật thành công");
    }

    public function delete($id)
    {
        $this->permissionsService->deleteByID($id);
        return $this->sendResponse();
    }
}

resources/views/admin/permissions/create.blade.php
<div class="modal fade" id="create-permission" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Thêm mới permission</h5>
            </div>
            <form data-url="{{ route('admin.permission.store') }}" id="formCreatePermission" method="POST">
                @csrf
                <div class="modal-body">
                    <div class="form-group mb-3">
                        <label for="">Name</label>
                        <input type="text" name="name" class="form-control">
                    </div>

                    <div class="form-group mb-3">
                        <label for="">Action</label>
                        <input type="text" name="action" class="form-control">
                        <span class="text-danger d-none" id="actionError"></span>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Đóng</button>
                    <button type="submit" class="btn btn-primary">Gửi</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/admin/permissions/index.blade.php
@extends('admin.layouts.main')

@section('content')
    <div class="page-content">
        <h4 class="text-uppercase">Permissions</h4>
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="d-flex align-items-center justify-content-between">
                        @can('permission.create')
                            <div class="col-lg-4 col-xl-4">
                                <a href="" class="btn btn-primary mb-3 mb-lg-0" data-bs-toggle="modal"
                                    data-bs-target="#create-permission">
                                    <i class="bx bxs-plus-square"></i>Thêm mới
                                </a>
                            </div>
                        @endcan
                        @include('admin.components.search', ['route' => route("admin.permission.index")])
                    </div>
                </div>
                @include("admin.components.notification")
                @include("admin.permissions.list")
            </div>
            {{ $permissions->links() }}
        </div>

        {{-- Modal for create product --}}
        @include('admin.permissions.create')
        {{-- Modal for update product --}}
        @include('admin.permissions.update')
    </div>
@endsection

resources/views/admin/permissions/list.blade.php
<table class="table mt-4">
    <thead class="table-dark">
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Name</th>
            <th scope="col">Action</th>
            <th scope="col">Created At</th>
            @can(['permission.delete', 'permission.update'])
                <th scope="col">Actions</th>
            @endcan
        </tr>
    </thead>
    <tbody>
        @foreach ($permissions as $permission)
            <tr>
                <td>{{ $permission->id }}</td>
                <td>{{ $permission->name }}</td>
                <td>{{ $permission->action }}</td>
                <td>{{ date_format($permission->created_at, 'd/m/Y H:i:s') }}</td>
                <td>
                    @can(['permission.update'])
                        <a class="btn btn-success update-buttuon" 
                            data-url="{{ route("admin.permission.update", ['id' => $permission->id]) }}"
                            data-bs-toggle="modal" data-bs-target="#update-permission">
                            <i class="bx bx-edit mr-0"></i>
                        </a>
                    @endcan

                    @can(['permission.delete'])
                        <a class="btn btn-danger delete-button"
                            data-url="{{ route('admin.permission.delete', ['id' => $permission->id]) }}">
                            <i class="bx bx-trash mr-0"></i>
                        </a>
                    @endcan
                </td>
            </tr>
        @endforeach
    </tbody>
</table>

resources/views/admin/permissions/update.blade.php
<div class="modal fade" id="update-permission" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Cập nhật permission</h5>
            </div>
            <form id="formUpdatePermission" method="POST" data-url="{{ route('admin.permission.update') }}">
                @csrf
                <div class="modal-body">
                    <input type="hidden" name="id" id="id-permission">
                    <div class="form-group mb-3">
                        <label for="">Name</label>
                        <input type="text" name="name" class="form-control" id="name-permission">
                    </div>

                    <div class="form-group mb-3">
                        <label for="">Action</label>
                        <input type="text" name="action" class="form-control" id="action-permission">
                        <span class="text-danger d-none" id="actionUpdateError"></span>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Đóng</button>
                    <button type="submit" class="btn btn-primary submit-update">Gửi</a>
                </div>
            </form>
        </div>
    </div>
</div>